### ISSUE TITLE
ActionOptions in stage WAITING cause constant loads and unloads of all Dimensions

### ISSUE THREAD

**Issue by fraenkelc** [McJtyMods/MeeCreeps#42]
Versions:
Forge 14.23.3.2657
mcjtylib 1.12-2.6.7
Meecreeps 1.12-1.1.0

Yesterday our server went down after it started constantly loading and unloading all dimensions. Due to crossmod interactions on world load this lead to extremly high IO, memory issues and brought the server down. Restarts of the server did not fix the issue. 

this is the relevant stacktrace:
```
"Server thread" #21 prio=5 os_prio=0 tid=0x00007f555d66e800 nid=0x70de runnable [0x00007f54e2b37000]                                                                                                                  [71/800]
   java.lang.Thread.State: RUNNABLE
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.io.DataInputStream.readUTF(DataInputStream.java:661)
        at java.io.DataInputStream.readUTF(DataInputStream.java:564)
        at net.minecraft.nbt.NBTTagCompound.func_152448_b(NBTTagCompound.java:486)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:56)
        at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:63)
        at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58)
        at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58)
        at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58)
        at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496)
        at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58)
        at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133)
        at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88)
        at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:31)
        at net.minecraft.world.storage.MapStorage.func_75742_a(SourceFile:49)
        at pregenerator.impl.structure.StructureController.applyChanges(StructureController.java:100)
        at pregenerator.impl.structure.StructureController.init(StructureController.java:88)
        at pregenerator.impl.structure.StructureController.<init>(StructureController.java:33)
        at pregenerator.impl.structure.StructureManager.onWorldLoad(StructureManager.java:185)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_600_StructureManager_onWorldLoad_Load.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:249)
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:830)
        at mcjty.lib.varia.TeleportationTools.getWorldForDimension(TeleportationTools.java:48)
        at mcjty.meecreeps.actions.ServerActionManager.findMeeCreep(ServerActionManager.java:247)
        at mcjty.meecreeps.actions.ServerActionManager.tick(ServerActionManager.java:263)
        at mcjty.meecreeps.ForgeEventHandlers.onWorldTick(ForgeEventHandlers.java:33)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_894_ForgeEventHandlers_onWorldTick_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
```

The Issue seems to be an ActionOption in stage WAITING.: 
![image](https://user-images.githubusercontent.com/4005102/38638228-eea602e6-3dcd-11e8-8235-4ba61a876615.png)

Looking at the code I suspect sombody started summoning a meecreep and dced / caused the area to unload before it finished. The ActionOption is not removed from the list if the chunk is not loaded in https://github.com/McJty/MeeCreeps/blob/cadd39e5566b4d39e4998280475a4ec4944241d3/src/main/java/mcjty/meecreeps/actions/ServerActionManager.java#L268-L276 
Since the area is outside of the spawn chunks it is also unloaded on server start this issue also occurs directly after the world is loaded after a server restart.

The above situation looks like the summon of a MeeCreep will always cause loads and unloads of all dimensions on the server. This feels quite excessive to me.

The Issue is easy to reproduce with just Meecreeps installed using the attached MeeCreepsData.dat taken from our server. Just create a new world, close it, replace the MeeCreepsData and join the world again. You should get lots of world loads and unloads in the log.

[latest.zip](https://github.com/McJty/MeeCreeps/files/1900250/latest.zip)
[MeeCreepsData.zip](https://github.com/McJty/MeeCreeps/files/1900126/MeeCreepsData.zip)

**Comment by SynexWolf** [comment]
Issue can be closed as the issue is fixed in the latest version.

**Comment by fraenkelc** [comment]
I've retested the issue and can confirm that the changes in 1.12-1.2.0 fix the issue.
