### ISSUE TITLE
Right clicking on door with Mee creep causes server crash - Direwolf 20 2.0 Beta

### ISSUE THREAD

**Issue by Shadowrayn** [McJtyMods/MeeCreeps#52]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (elulib-0.1.12.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3206.jar)
  CTMCorePlugin (CTM-MC1.12-0.3.0.15.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b155.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AstralCore (astralsorcery-1.12.2-1.9.1.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 7/8/18 4:35 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at mcjty.lostcities.dimensions.world.LostWorldProvider.getSaveFolder(LostWorldProvider.java:28)
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:759)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:4150)
	at mcjty.lib.varia.TeleportationTools.getWorldForDimension(TeleportationTools.java:48)
	at mcjty.meecreeps.actions.ServerActionManager.findMeeCreep(ServerActionManager.java:234)
	at mcjty.meecreeps.actions.ServerActionManager.tick(ServerActionManager.java:250)
	at mcjty.meecreeps.ForgeEventHandlers.onWorldTick(ForgeEventHandlers.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_964_ForgeEventHandlers_onWorldTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:662)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:597)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.lostcities.dimensions.world.LostWorldProvider.getSaveFolder(LostWorldProvider.java:28)
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:759)
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:4150)
	at mcjty.lib.varia.TeleportationTools.getWorldForDimension(TeleportationTools.java:48)
	at mcjty.meecreeps.actions.ServerActionManager.findMeeCreep(ServerActionManager.java:234)
	at mcjty.meecreeps.actions.ServerActionManager.tick(ServerActionManager.java:250)
	at mcjty.meecreeps.ForgeEventHandlers.onWorldTick(ForgeEventHandlers.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_964_ForgeEventHandlers_onWorldTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:662)

**Comment by McJty** [comment]
What version of MeeCreeps mod?

**Comment by Shadowrayn** [comment]
1.2.0

**Comment by McJty** [comment]
This bug should be fixed in 1.2.1. Try updating and if it still fails then please let me know
